# Tensor based approach to Spearman's pitch control

Code from anenglishgoat [https://github.com/anenglishgoat/Metrica-pitch-control/blob/master/FastSpearmanPitchControl.ipynb ] <br>

This approach used Gauss-Legendre Quadratation for numerical integration! <br>

In [3]:
import pandas as pd
import numpy as np
import torch
from torch.nn.functional import softplus

In [4]:
### load the data and process it
away_data = pd.read_csv('https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Away_Team.csv', skiprows=2)
home_data = pd.read_csv('https://raw.githubusercontent.com/metrica-sports/sample-data/master/data/Sample_Game_1/Sample_Game_1_RawTrackingData_Home_Team.csv', skiprows=2)


In [5]:
away_data

Period   Frame  Time [s]  Player25  Unnamed: 4  Player15  Unnamed: 6  \
0            1       1      0.04   0.90509     0.47462   0.58393     0.20794   
1            1       2      0.08   0.90494     0.47462   0.58393     0.20794   
2            1       3      0.12   0.90434     0.47463   0.58393     0.20794   
3            1       4      0.16   0.90377     0.47463   0.58351     0.20868   
4            1       5      0.20   0.90324     0.47464   0.58291     0.21039   
...        ...     ...       ...       ...         ...       ...         ...   
145001       2  145002   5800.08   0.12564     0.55386   0.17876     0.56826   
145002       2  145003   5800.12   0.12564     0.55386   0.17838     0.56727   
145003       2  145004   5800.16   0.12564     0.55386   0.17792     0.56682   
145004       2  145005   5800.20   0.12564     0.55386   0.17730     0.56621   
145005       2  145006   5800.24   0.12564     0.55386   0.17693     0.56675   

        Player16  Unnamed: 8  Player17  ...  Player24  Unnamed: 24  Player26  \
0        0.67658     0.46710   0.67310  ...   0.37833      0.27383       NaN   
1        0.67658     0.46710   0.67310  ...   0.37833      0.27383       NaN   
2        0.67658     0.46710   0.67310  ...   0.37833      0.27383       NaN   
3        0.67640     0.46762   0.67279  ...   0.37756      0.27473       NaN   
4        0.67599     0.46769   0.67253  ...   0.37663      0.27543       NaN   
...          ...         ...       ...  ...       ...          ...       ...   
145001   0.25818     0.59952   0.09880  ...       NaN          NaN   0.35600   
145002   0.25799     0.59999   0.09880  ...       NaN          NaN   0.35583   
145003   0.25757     0.60019   0.09880  ...       NaN          NaN   0.35561   
145004   0.25721     0.60089   0.09880  ...       NaN          NaN   0.35532   
145005   0.25659     0.60072   0.09880  ...       NaN          NaN   0.35495   

        Unnamed: 26  Player27  Unnamed: 28  Player28  Unnamed: 30     Ball  \
0               NaN       NaN          NaN       NaN          NaN  0.45472   
1               NaN       NaN          NaN       NaN          NaN  0.49645   
2               NaN       NaN          NaN       NaN          NaN  0.53716   
3               NaN       NaN          NaN       NaN          NaN  0.55346   
4               NaN       NaN          NaN       NaN          NaN  0.55512   
...             ...       ...          ...       ...          ...      ...   
145001      0.55371   0.19836      0.45137   0.21798      0.81079      NaN   
145002      0.55283   0.19831      0.45182   0.21798      0.81079      NaN   
145003      0.55254   0.19805      0.45200   0.21798      0.81079      NaN   
145004      0.55243   0.19766      0.45237   0.21798      0.81079      NaN   
145005      0.55364   0.19754      0.45364   0.21798      0.81079      NaN   

        Unnamed: 32  
0           0.38709  
1           0.40656  
2           0.42556  
3           0.42231  
4           0.40570  
...             ...  
145001          NaN  
145002          NaN  
145003          NaN  
145004          NaN  
145005          NaN  

[145006 rows x 33 columns]

In [6]:
device = 'cpu'; dtype = torch.float32


jitter = 1e-12 ## prevents division by zero when player is stationary

## set nans to large negative value -- this makes pitch control for players who aren't involved negligibly small everywhere
# on the pitch
home_pos = np.array([np.asarray(home_data.iloc[:,range(3 + j*2,3 + j*2 +2)]) for j in range(14)]) * np.array([105,68])
np.nan_to_num(home_pos,copy=False,nan=-1000)
away_pos = np.array([np.asarray(away_data.iloc[:,range(3 + j*2,3 + j*2 +2)]) for j in range(14)]) * np.array([105,68])
np.nan_to_num(away_pos,copy=False,nan=-1000)
ball_pos = (np.asarray(home_data.iloc[:,range(31,33)]) * np.array([105,68]))[:,None,None,:]


# defining the delta in seconds between frames
tt = np.asarray(home_data['Time [s]'])
dt = tt[1:] - tt[:-1] 
# velocity in both x and y axis + jitter 
# jitter prevents division by zero when player is stationary
home_v = (home_pos[:,1:,:] - home_pos[:,:-1,:])/dt[:,None] + jitter
np.nan_to_num(home_v,copy=False,nan=-1000)
away_v = (away_pos[:,1:,:] - away_pos[:,:-1,:])/dt[:,None] + jitter
np.nan_to_num(away_v,copy=False,nan=-1000)
# velocity -1000 not really necessary?

print(home_pos.shape, away_pos.shape, ball_pos.shape, home_v.shape, away_v.shape)

(14, 145006, 2) (14, 145006, 2) (145006, 1, 1, 2) (14, 145005, 2) (14, 145005, 2)


In [10]:
home_pos[:,1:,:]

array([[[ 1.008000e-01,  3.280184e+01],
        [ 1.197000e-01,  3.280184e+01],
        [ 1.270500e-01,  3.280184e+01],
        ...,
        [ 9.501660e+01,  3.084140e+01],
        [ 9.497880e+01,  3.084208e+01],
        [ 9.497880e+01,  3.084208e+01]],

       [[ 3.428040e+01,  4.441896e+01],
        [ 3.428040e+01,  4.441896e+01],
        [ 3.425310e+01,  4.441556e+01],
        ...,
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03]],

       [[ 3.538605e+01,  3.322684e+01],
        [ 3.538605e+01,  3.322684e+01],
        [ 3.537135e+01,  3.331184e+01],
        ...,
        [ 3.579345e+01,  4.390692e+01],
        [ 3.575880e+01,  4.389536e+01],
        [ 3.569580e+01,  4.388992e+01]],

       ...,

       [[-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        ...,
        [ 3.154620e+01,  4.645148e+01],
        [ 3.154620e+01,  4.645148e+01],
        [

In [11]:
home_pos

array([[[ 8.610000e-02,  3.280184e+01],
        [ 1.008000e-01,  3.280184e+01],
        [ 1.197000e-01,  3.280184e+01],
        ...,
        [ 9.501660e+01,  3.084140e+01],
        [ 9.497880e+01,  3.084208e+01],
        [ 9.497880e+01,  3.084208e+01]],

       [[ 3.428040e+01,  4.441896e+01],
        [ 3.428040e+01,  4.441896e+01],
        [ 3.428040e+01,  4.441896e+01],
        ...,
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03]],

       [[ 3.538605e+01,  3.322684e+01],
        [ 3.538605e+01,  3.322684e+01],
        [ 3.538605e+01,  3.322684e+01],
        ...,
        [ 3.579345e+01,  4.390692e+01],
        [ 3.575880e+01,  4.389536e+01],
        [ 3.569580e+01,  4.388992e+01]],

       ...,

       [[-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        [-1.000000e+03, -1.000000e+03],
        ...,
        [ 3.154620e+01,  4.645148e+01],
        [ 3.154620e+01,  4.645148e+01],
        [

In [12]:

# what is the point of this block
home_pos = home_pos[:,1:,None,None,:]
away_pos = away_pos[:,1:,None,None,:]
home_v = home_v[:,:,None,None,:]
away_v = away_v[:,:,None,None,:]
ball_pos = ball_pos[None,1:]

print(home_pos.shape, away_pos.shape, ball_pos.shape, home_v.shape, away_v.shape)

(14, 145005, 1, 1, 2) (14, 145005, 1, 1, 2) (1, 145005, 1, 1, 2) (14, 145005, 1, 1, 2) (14, 145005, 1, 1, 2)


In [13]:
away_pos

array([[[[[   95.0187 ,    32.27416]]],


        [[[   94.9557 ,    32.27484]]],


        [[[   94.89585,    32.27484]]],


        ...,


        [[[   13.1922 ,    37.66248]]],


        [[[   13.1922 ,    37.66248]]],


        [[[   13.1922 ,    37.66248]]]],



       [[[[   61.31265,    14.13992]]],


        [[[   61.31265,    14.13992]]],


        [[[   61.26855,    14.19024]]],


        ...,


        [[[   18.6816 ,    38.54376]]],


        [[[   18.6165 ,    38.50228]]],


        [[[   18.57765,    38.539  ]]]],



       [[[[   71.0409 ,    31.7628 ]]],


        [[[   71.0409 ,    31.7628 ]]],


        [[[   71.022  ,    31.79816]]],


        ...,


        [[[   27.04485,    40.81292]]],


        [[[   27.00705,    40.86052]]],


        [[[   26.94195,    40.84896]]]],



       ...,



       [[[[-1000.     , -1000.     ]]],


        [[[-1000.     , -1000.     ]]],


        [[[-1000.     , -1000.     ]]],


        ...,


        [[[   37.33905,    37.57272]]

In [14]:
n_grid_points_x = 50
n_grid_points_y = 30
# create grid based on tensors
XX,YY = torch.meshgrid(torch.linspace(0,105,n_grid_points_x, device = device, dtype=dtype),
                       torch.linspace(0,68,n_grid_points_y,device=device,dtype=dtype))

print(XX.shape, YY.shape)

torch.Size([50, 30]) torch.Size([50, 30])


C:\Users\DavidB\PycharmProjects\My_Football_Analytics\Football_Analytics_venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


In [15]:
ti,wi = np.polynomial.legendre.leggauss(50) ## used for numerical integration later on
ti = torch.tensor(ti,device = device,dtype=dtype)
wi = torch.tensor(wi,device=device,dtype=dtype)
print(ti, wi)

tensor([-0.9989, -0.9940, -0.9854, -0.9729, -0.9566, -0.9367, -0.9131, -0.8860,
        -0.8554, -0.8216, -0.7846, -0.7445, -0.7016, -0.6559, -0.6077, -0.5572,
        -0.5045, -0.4498, -0.3934, -0.3355, -0.2763, -0.2160, -0.1549, -0.0932,
        -0.0311,  0.0311,  0.0932,  0.1549,  0.2160,  0.2763,  0.3355,  0.3934,
         0.4498,  0.5045,  0.5572,  0.6077,  0.6559,  0.7016,  0.7445,  0.7846,
         0.8216,  0.8554,  0.8860,  0.9131,  0.9367,  0.9566,  0.9729,  0.9854,
         0.9940,  0.9989]) tensor([0.0029, 0.0068, 0.0106, 0.0144, 0.0181, 0.0218, 0.0254, 0.0288, 0.0322,
        0.0355, 0.0386, 0.0415, 0.0443, 0.0470, 0.0494, 0.0517, 0.0537, 0.0556,
        0.0572, 0.0586, 0.0598, 0.0607, 0.0615, 0.0619, 0.0622, 0.0622, 0.0619,
        0.0615, 0.0607, 0.0598, 0.0586, 0.0572, 0.0556, 0.0537, 0.0517, 0.0494,
        0.0470, 0.0443, 0.0415, 0.0386, 0.0355, 0.0322, 0.0288, 0.0254, 0.0218,
        0.0181, 0.0144, 0.0106, 0.0068, 0.0029])


In [16]:
target_position = torch.stack([XX,YY],2)[None,None,:,:,:] # all possible positions
target_position

tensor([[[[[  0.0000,   0.0000],
           [  0.0000,   2.3448],
           [  0.0000,   4.6897],
           ...,
           [  0.0000,  63.3103],
           [  0.0000,  65.6552],
           [  0.0000,  68.0000]],

          [[  2.1429,   0.0000],
           [  2.1429,   2.3448],
           [  2.1429,   4.6897],
           ...,
           [  2.1429,  63.3103],
           [  2.1429,  65.6552],
           [  2.1429,  68.0000]],

          [[  4.2857,   0.0000],
           [  4.2857,   2.3448],
           [  4.2857,   4.6897],
           ...,
           [  4.2857,  63.3103],
           [  4.2857,  65.6552],
           [  4.2857,  68.0000]],

          ...,

          [[100.7143,   0.0000],
           [100.7143,   2.3448],
           [100.7143,   4.6897],
           ...,
           [100.7143,  63.3103],
           [100.7143,  65.6552],
           [100.7143,  68.0000]],

          [[102.8571,   0.0000],
           [102.8571,   2.3448],
           [102.8571,   4.6897],
           ...,
     

In [17]:
n_frames = home_pos.shape[1]
first_frame = 0
batch_size = 250

# time to intercept empty torch
tti = torch.empty([28,batch_size,n_grid_points_x,n_grid_points_y],device = device,dtype=dtype)
# 28 players*500 batches*grid
tmp2 = torch.empty([28,batch_size,n_grid_points_x,n_grid_points_y,1],device = device,dtype=dtype)
# 28 players*500 batches*grid * 1
pc = torch.empty([n_frames,n_grid_points_x,n_grid_points_y],device = device,dtype=dtype)
# frames * grid

print(tti.shape, tmp2.shape, pc.shape)

torch.Size([28, 250, 50, 30]) torch.Size([28, 250, 50, 30, 1]) torch.Size([145005, 50, 30])


In [18]:
device = 'cpu'; dtype = torch.float32


jitter = 1e-12 ## prevents division by zero when player is stationary

## set nans to large negative value -- this makes pitch control for players who aren't involved negligibly small everywhere
# on the pitch
home_pos = np.array([np.asarray(home_data.iloc[:,range(3 + j*2,3 + j*2 +2)]) for j in range(14)]) * np.array([105,68])
np.nan_to_num(home_pos,copy=False,nan=-1000)
away_pos = np.array([np.asarray(away_data.iloc[:,range(3 + j*2,3 + j*2 +2)]) for j in range(14)]) * np.array([105,68])
np.nan_to_num(away_pos,copy=False,nan=-1000)
ball_pos = (np.asarray(home_data.iloc[:,range(31,33)]) * np.array([105,68]))[:,None,None,:]


# defining the delta in seconds between frames
tt = np.asarray(home_data['Time [s]'])
dt = tt[1:] - tt[:-1] 
# velocity in both x and y axis + jitter 
# jitter prevents division by zero when player is stationary
home_v = (home_pos[:,1:,:] - home_pos[:,:-1,:])/dt[:,None] + jitter
np.nan_to_num(home_v,copy=False,nan=-1000)
away_v = (away_pos[:,1:,:] - away_pos[:,:-1,:])/dt[:,None] + jitter
np.nan_to_num(away_v,copy=False,nan=-1000)
# velocity -1000 not really necessary?




# severe changes in the shape of the arrays
# I am not 100% how and why this is necessary
# This is probably necessary for later 
home_pos = home_pos[:,1:,None,None,:]
away_pos = away_pos[:,1:,None,None,:]
home_v = home_v[:,:,None,None,:]
away_v = away_v[:,:,None,None,:]
ball_pos = ball_pos[None,1:]


## set up evaluation grid and set some pitch control parameters (these are taken from the FoT code)
reaction_time = 0.7
max_player_speed = 5.
average_ball_speed = 15.
sigma = np.pi / np.sqrt(3.) / 0.45
lamb = 4.3
n_grid_points_x = 50
n_grid_points_y = 30
# create grid based on tensors
XX,YY = torch.meshgrid(torch.linspace(0,105,n_grid_points_x, device = device, dtype=dtype),
                       torch.linspace(0,68,n_grid_points_y,device=device,dtype=dtype))
target_position = torch.stack([XX,YY],2)[None,None,:,:,:] # all possible positions


# the weights and the x-points of the Gauss–Legendre quadrature are set up and stored as torch tensors
# I assume that, as the Gauss–Legendre quadrature spans the range of [-1, 1] (length of 2), the 50 points selected
# represent the number of frames in a 2 second time period based on a framerate of 25Hz (i.e. 25 frames / second)
ti,wi = np.polynomial.legendre.leggauss(50) ## used for numerical integration later on
ti = torch.tensor(ti,device = device,dtype=dtype)
wi = torch.tensor(wi,device=device,dtype=dtype)




n_frames = home_pos.shape[1]
first_frame = 0
batch_size = 250

# time to intercept empty torch
tti = torch.empty([28,batch_size,n_grid_points_x,n_grid_points_y],device = device,dtype=dtype)
# 28 players*500 batches*grid
tmp2 = torch.empty([28,batch_size,n_grid_points_x,n_grid_points_y,1],device = device,dtype=dtype)
# 28 players*500 batches*grid * 1
pc = torch.empty([n_frames,n_grid_points_x,n_grid_points_y],device = device,dtype=dtype)
# frames * grid

# for f in range(int(n_frames/batch_size)):
# taking 500 frames or the last frames if less than 500 left
for f in range(1): 
    
    bp = torch.tensor(ball_pos[:,(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,
                                                                          int(first_frame + n_frames)))],
                      device = device,dtype=dtype)
    hp = torch.tensor(home_pos[:,(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,
                                                                          int(first_frame + n_frames)))],
                      device = device,dtype=dtype)
    hv = torch.tensor(home_v[:,(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,
                                                                        int(first_frame + n_frames)))],
                      device = device,dtype=dtype)
    ap = torch.tensor(away_pos[:,(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,
                                                                          int(first_frame + n_frames)))],
                      device = device,dtype=dtype)
    av = torch.tensor(away_v[:,(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,
                                                                        int(first_frame + n_frames)))],
                      device = device,dtype=dtype)
    
    ball_travel_time = torch.norm(target_position - bp, dim=4).div_(average_ball_speed) 
    # ball travel time to each location in each frame in the batch
    
    r_reaction_home = hp + hv.mul_(reaction_time) # position after reaction time (vector)
    r_reaction_away = ap + av.mul_(reaction_time) # = position + velocity multiplied by reaction time
    r_reaction_home = r_reaction_home - target_position # distance to target position (vector)
    r_reaction_away = r_reaction_away - target_position # after reaction time
    
    # time to intercept for home and away filled 
    # torch.norm --> distance of position in grid to target position from vector to value
    # add reaction time to time of intercept
    # divide distance by speed --> time of intercept
    # i think it should be the other way around! Divide first and then add reaction time
    tti[:14,:ball_travel_time.shape[1]] = torch.norm(r_reaction_home,dim=4).add_(reaction_time).div_(max_player_speed)
    tti[14:,:ball_travel_time.shape[1]] = torch.norm(r_reaction_away,dim=4).add_(reaction_time).div_(max_player_speed)
    # tti[:14,:ball_travel_time.shape[1]] = torch.norm(r_reaction_home,dim=4).div_(max_player_speed).add_(reaction_time)
    # tti[14:,:ball_travel_time.shape[1]] = torch.norm(r_reaction_away,dim=4).div_(max_player_speed).add_(reaction_time)

    tmp2[...,0] = sigma * (ball_travel_time - tti)
    
    tmp1 = sigma * 0.5 * (ti + 1) * 10 + tmp2
    
    # every players (scaled) time to control fed into a sigmoid function
    # --> probabilites [0,1], multiplied by lambda (default 4.3) --> range of [0, 4.3]
    hh = torch.sigmoid(tmp1[:14]).mul_(4.3)
    # teams intercept probability as the sum of players' control probabilities
    h = hh.sum(0)
    
    S = torch.exp(-lamb*torch.sum(softplus(tmp1) - softplus(tmp2),dim=0).div_(sigma))

    # numerische Integralbildung durch Gewichte (wi) durch Matrixvektorprukt aus Sh und den Gewichten 
    # i.e. Gewicht wird mit dem Entsprechenden der 50 Werte aus der Verteilung multipliziert
    pc[(first_frame + f*batch_size):(np.minimum(first_frame + (f+1)*batch_size,int(first_frame + n_frames)))] = torch.matmul(S*h,wi).mul_(5.)


In [21]:
pc.shape

torch.Size([145005, 50, 30])

## Exploration

In [ ]:
print(f'Minimum of tmp2: {tmp2.min()}, Maximum of tmp2: {tmp2.max()}, shape: {tmp2.shape}')
# --> + [0.0228, 40.02838] = time to intercept (scaled by sigma)
print(f'Minimum of tmp1: {tmp1.min()}, Maximum of tmp1: {tmp1.max()}, shape: {tmp1.shape}')
# tmp1 =  distribution of possible times to intercept available (scaled by sigma)
# tmp2 =  single estimate time to intercept (scaled by sigma) = exponent of intercept probability equation (3)

In [ ]:
Diff = softplus(tmp1) - softplus(tmp2)
print(f'Minimum of Diff: {Diff.min()}, Maximum of Diff: {Diff.max()}, shape: {Diff.shape}')
# The difference is just the distribution of values between 0 and 40.28 (only roughly because of negative value handling in softplus)


In [ ]:
Diff_sum = torch.sum(softplus(tmp1) - softplus(tmp2),dim=0)
print(f'Minimum of Diff: {Diff_sum.min()}, Maximum of Diff: {Diff_sum.max()}, shape: {Diff_sum.shape}')
# sum of all 28 players 

In [ ]:
exp = -lamb*torch.sum(softplus(tmp1) - softplus(tmp2),dim=0).div_(sigma)
print(f'Minimum of exp: {exp.min()}, Maximum of exp: {exp.max()}, shape: {exp.shape}')


In [ ]:
S = torch.exp(-lamb*torch.sum(softplus(tmp1) - softplus(tmp2),dim=0).div_(sigma))
print(f'Minimum of S: {S.min()}, Maximum of S: {S.max()}, shape: {S.shape}')
# transforms the whole thing to a range of [0, 1]
# = control probability -1 based on all possible times to control?!  

In [ ]:
hh = torch.sigmoid(tmp1[:14]).mul_(4.3)
print(f'Minimum of hh: {hh.min()}, Maximum of hh: {hh.max()}, shape: {hh.shape}')
# converts time available to intercept the ball into a probability [0,1] --> hints at intercept probability
# sigmoid with tmp1 as the exponent is exactly the intercept probability function (3)
# why multiply by lambda?! Makes no sense to me
# only for the home team!

# teams intercept probability as the sum of players' intercept probabilities
h = hh.sum(0)
print(f'Minimum of h: {h.min()}, Maximum of h: {h.max()}, shape: {h.shape}')


In [ ]:
print(f'Minimum of pc: {pc.min()}, Maximum of pc: {pc.max()}, shape: {pc.shape}')

In [ ]:
hh

In [ ]:
S